import Image from 'next/image';
import React from 'react';

interface NavigationProps {
    children?: React.ReactNode;
    className?: string;
}

export const metadata = {
  title: 'JAAACK',
  description: 'Generated by create next app',
}

export default function Navigation({children, className}: NavigationProps) {
  return (
    <header className={`${className} md:w-24 md:h-screen md:fixed md:top-0 py-4 md:bg-white md:bg-opacity-50`}>
      <nav>
      </nav>
      <Image
        src="/logo.png"
        alt="Jaaack Logo"
        className="invert max-w-none"
        width={160}
        height={24}
        priority
      />
    </header>
  )
}